import meat1 from "../images/products/meat1.webp";
import meat2 from "../images/products/meat-2.webp";
import meat3 from "../images/products/meat-3.webp";
import meat4 from "../images/products/meat-4.webp";
import meat5 from "../images/products/meat-5.webp";
import milk1 from "../images/products/milk-1.webp";
import milk2 from "../images/products/milk-2.webp";
import milk3 from "../images/products/milk-3.webp";
import milk4 from "../images/products/milk-4.webp";
import milk5 from "../images/products/milk-5.webp";
import milk6 from "../images/products/milk6.jpeg";
import milk7 from "../images/products/milk7.jpeg";
import milk8 from "../images/products/milk8.jpeg";
import milk9 from "../images/products/milk9.jpeg";
import milk10 from "../images/products/milk10.jpeg";
import milk11 from "../images/products/milk11.jpeg";
import milk12 from "../images/products/milk12.jpeg";
import milk13 from "../images/products/milk13.png";
import milk14 from "../images/products/milk14.jpeg";
import milk15 from "../images/products/milk15.jpeg";
import milk16 from "../images/products/milk16.jpeg";
import milk17 from "../images/products/milk17.jpeg";
import milk18 from "../images/products/milk18.jpeg";
import milk19 from "../images/products/milk19.jpeg";
import milk20 from "../images/products/milk20.jpeg";
import milk21 from "../images/products/milk21.jpeg";
import milk22 from "../images/products/milk22.jpeg";
import milk23 from "../images/products/milk23.jpeg";
import milk24 from "../images/products/milk24.jpeg";
import milk25 from "../images/products/milk25.jpeg";
import milk26 from "../images/products/milk26.jpeg";
import milk27 from "../images/products/milk27.jpeg";
import milk28 from "../images/products/milk28.jpeg";
import milk29 from "../images/products/milk29.jpeg";
import milk31 from "../images/products/milk31.jpeg";
import milk32 from "../images/products/milk32.jpeg";

export const ProductsList = [
  {
    id: 1,
    name: "Фарш Ближние горки деревенский охлажденный 400г",
    brend: "Ближние Горки",
    description:
      "Фарш «Деревенский» содержит много питательных веществ, поэтому любое кулинарное изделие, приготовленное из него, будет не только вкусным, но и полезным. Этот полуфабрикат бренда «Ближние Горки» из свинины и говядины высшего сорта. Из него можно сделать сотню праздничных блюд и обедов на каждый день. Это сочное и ароматное мясо подходит для приготовления котлет, рулетов, мясных запеканок, бифштексов и пирожков.",
    price: 149,
    cents: 90,
    image: meat1,
    country: "Россия",
    calories: 418,
    proteins: 10,
    fats: 42,
    carbohydrates: 0,
    category: "meat",
    subcategories: "groundmeat",
    type: "popular",
  },
  {
    id: 2,
    name: "Бедро цыпленка-бройлера Петелинка в упаковке",
    brend: "Петелинка",
    description:
      "Бедро Особое Петелинка - часть тушки с сочным и вкусным мясом. Куриные бедра содержат много полезных веществ. Существует большое количество рецептов из этого продукта, а приготовление займет минимальное количество времени. Петелинка – это чистый продукт без вредных добавок, ГМО и гормонов роста. Гарантия всегда свежего продукта.",
    price: 319,
    cents: 90,
    image: meat2,
    country: "Россия",
    calories: 190,
    proteins: 17,
    fats: 13,
    carbohydrates: 0,
    category: "meat",
    subcategories: "bird",
    type: "popular",
  },
  {
    id: 3,
    name: "Мини-котлетки куриные Мираторг с моцареллой 380г",
    brend: "Мираторг",
    description:
      "Отлично сочетается с куриным мясом, придает ему нежный вкус и аромат. Во время приготовления начинка пропитывает мясо и придаёт ему насыщенный вкус и аромат. А хрустящая сухарная панировка сдерживает весь сок внутри. Обжарьте котлеты с двух сторон до золотистой корочки, убавьте огонь и доведите до готовности под крышкой.",
    price: 159,
    cents: 90,
    image: meat3,
    country: "Россия",
    calories: 258,
    proteins: 9,
    fats: 14,
    carbohydrates: 24,
    category: "meat",
    subcategories: "cutlet",
    type: "popular",
  },
  {
    id: 4,
    name: "Чевапчичи Слово мясника охлажденные 300г",
    brend: "Слово Мясника",
    description:
      "Чевапчичи из свинины и говядины рубленые от бренда СЛОВО МЯСНИКА – вкусный полуфабрикат. Ароматные колбаски из рубленой свинины и говядины с луком и специями внесут разнообразие в меню любимых блюд для гриля. А если вы решили остаться дома, приготовьте чевапчичи в духовке. Попробуйте пряные чевапчичи – традиционное блюдо балканской кухни.",
    price: 119,
    cents: 90,
    image: meat4,
    country: "Россия",
    calories: 360,
    proteins: 12,
    fats: 35,
    carbohydrates: 0,
    category: "meat",
    subcategories: "bird",
    type: "popular",
  },
  {
    id: 5,
    name: "Ребрышки свиные Черкизово Аппетитные в маринаде",
    brend: "Черкизово",
    description:
      "Ребрышки аппетитные в маринаде достойны своего названия. Мясо получается необыкновенно сочным, а благодаря особым приправам - пряным и ароматным. И что немаловажно, его легко приготовить. Вам лишь надо удалить этикетку, сделать небольшое надрез в верхней части пакета, уложить пакет на холодный противень и поставить в разогретую духовку.",
    price: 369,
    cents: 90,
    image: meat5,
    country: "Россия",
    calories: 292,
    proteins: 19,
    fats: 20,
    carbohydrates: 2,
    category: "meat",
    subcategories: "pork",
    type: "popular",
  },
  {
    id: 6,
    name: "Молоко Простоквашино пастеризованное 2,5% 930мл",
    brend: "Простоквашино",
    description:
      "Молоко Простоквашино отлично дополнит ваш завтрак, его можно добавить в кофе или чай или выпить на ночь. Кроме того, оно отлично подойдет для готовки блинчиков, каш и множества других любимых домашних блюд. Пейте Молоко Простоквашино с удовольствием!",
    price: 81,
    cents: 99,
    image: milk1,
    country: "Россия",
    calories: 53,
    proteins: 3,
    fats: 2.5,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 7,
    name: "Молоко ультрапастеризованное Домик в деревне 3,2% 950г",
    brend: "Домик в деревне",
    description:
      "Молоко «Домик в деревне» – 100% натуральный продукт, приготовленный по традиционным рецептам. «Домик в деревне» - все, что мы узнали о натуральности, мы узнали от бабушек. 100% натуральное молоко. Без добавления консервантов и красителей. Жирность 3,2% подходит для тех, кто любит традиционный вкус молока. Пить молоко «Домик в деревне» можно холодным и тёплым. Идеально для кофе, чая и приготовления ваших любимых блюд.",
    price: 108,
    cents: 90,
    image: milk2,
    country: "Россия",
    calories: 60,
    proteins: 3.1,
    fats: 3.2,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 8,
    name: "Молоко Село Зеленое ультрапастеризованное 3,2, 950мл",
    brend: "Село Зеленое",
    description:
      "Молоко «Село Зелёное» 3,2% – полезный для здоровья натуральный и экологичный продукт высшего качества. Высококачественное сырье, новейшие технологии обработки и современные упаковочные решения позволяют надолго сохранять натуральный продукт без использования консервантов.",
    price: 99,
    cents: 99,
    image: milk3,
    country: "Россия",
    calories: 60,
    proteins: 3,
    fats: 3.2,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 9,
    name: "Молоко ультрапастеризованное 2,5% в ассортименте 924мл/1000мл",
    brend: "Молоко ультрапастеризованное",
    description:
      "Молоко содержит целое множество полезностей для поддержания вашего организма в превосходном состоянии.",
    price: 96,
    cents: 99,
    image: milk4,
    country: "Россия",
    calories: 53.3,
    proteins: 2.5,
    fats: 3,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 10,
    name: "Молоко Хуторок 1,5% 900мл",
    brend: "Хуторок",
    description:
      "Свежее и настоящее молоко, созданное с любовью к родным и близким.",
    price: 69,
    cents: 99,
    image: milk5,
    country: "Россия",
    calories: 44,
    proteins: 3,
    fats: 1.5,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 11,
    name: "Яйцо куриное столовое 1 категория в ассортименте 10шт",
    brend: "Тендер",
    description:
      "Только свежее и отборное яйцо. Мы используем современные технологии изготовления кормов, которые позволяют сохранить в них все необходимые питательные вещества и витамины.",
    price: 36,
    cents: 49,
    image: milk6,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 12,
    name: "Яйцо куриное Деревенские напевы 1 категории 10шт",
    brend: "Деревенские Напевы",
    description:
      'Яйцо куриное "Деревенские напевы" 1 категория - контейнер с одним десятком яиц первой категории. Каждое яйцо имеет вес 55–65 г.',
    price: 99,
    cents: 99,
    image: milk7,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 13,
    name: "Майонез Московский Провансаль Классический 67% 700мл",
    brend: "Московский провансаль",
    description:
      "Майонез Я ЛЮБЛЮ ГОТОВИТЬ Московский провансаль Классический 67% изготовлен из семи натуральных ингредиентов. Не содержит ГМО, красителей и консервантов.",
    price: 149,
    cents: 90,
    image: milk8,
    country: "Россия",
    calories: 619,
    proteins: 0.4,
    fats: 67,
    carbohydrates: 2.2,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 14,
    name: "Творог Хуторок 5% 180г",
    brend: "Хуторог",
    description:
      'Нежная творожная консистенция, легкая кислинка во вкусе. Творог "Хуторок" 5% идеально подходит для приготовления сырников и запеканок!',
    price: 69,
    cents: 99,
    image: milk9,
    country: "Россия",
    calories: 121,
    proteins: 16,
    fats: 5,
    carbohydrates: 3,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 15,
    name: "Йогурт греческий Teos Натуральный 2% 140г",
    brend: "Савушкин",
    description:
      'Йогурт "Teos" изготавливается по традиционной технологии процеживания, благодаря чему содержит в 2 раза больше белка в сравнении с классическими йогуртами и имеет невероятно густую, кремовую консистенцию.',
    price: 54,
    cents: 99,
    image: milk10,
    country: "Россия",
    calories: 62.8,
    proteins: 7,
    fats: 2,
    carbohydrates: 4.2,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 16,
    name: "Творог Хуторок 9% 300г",
    brend: "Хуторок",
    description:
      "Продукт обладает чистым выраженным кисломолочным вкусом, привлекательным ароматом и приятной консистенцией. Отлично подходит для завтраков, полезных перекусов.",
    price: 129,
    cents: 90,
    image: milk11,
    country: "Россия",
    calories: 157,
    proteins: 16,
    fats: 9,
    carbohydrates: 3,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 17,
    name: "Творог Хуторок 5% 300г",
    brend: "Хуторок",
    description:
      "Продукт обладает чистым выраженным кисломолочным вкусом, привлекательным ароматом и приятной консистенцией. Отлично подходит для завтраков, полезных перекусов.",
    price: 109,
    cents: 90,
    image: milk12,
    country: "Россия",
    calories: 121,
    proteins: 16,
    fats: 5,
    carbohydrates: 3,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 18,
    name: "Масло Экомилк Традиционное сливочное 82,5% 160г",
    brend: "Экомилк",
    description:
      "Масло сливочное Экомилк - продукт высшего сорта, изготовленный по традиционной рецептуре. Сырье для производства соответствует принятым современным нормам качества. Масло обладает ярким, насыщенным сливочным вкусом и оптимально подходит для заправки каш, спагетти и картофельного пюре.",
    price: 109,
    cents: 90,
    image: milk13,
    country: "Россия",
    calories: 748,
    proteins: 0.6,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 19,
    name: "Масло Брест-Литовск сливочное 82,5% 180г",
    brend: "Брест-Литовск",
    description:
      'Это масло готовится из свежих сливок: оцените его нежный вкус! Универсальное масло подойдет для любых блюд. Добавляйте в кашу, готовьте сэндвичи и канапе, смело используйте для выпечки - каждый рецепт станет удачным. "Брест-Литовск" - натуральные молочные продукты, которые готовятся по классическим рецептам. Благодаря сочетанию традиций и современных технологий белорусскому производителю удается радовать покупателя неизменным качеством из года в год.',
    price: 229,
    cents: 90,
    image: milk14,
    country: "Россия",
    calories: 747,
    proteins: 0.5,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 20,
    name: "Масса творожная РостАгроЭкспорт Особая с изюмом 180г",
    brend: "РостАгроЭкспорт",
    description:
      'Масса творожная "Особая с сахаром и изюмом" - это молочный продукт, который готовится без добавления консервантов и красителей. В состав творожного десерта входят исключительно натуральные ингредиенты. Цвет творожной массы приятный, нежно-бежевый, консистенция - рассыпчатая и однородная, с цельными изюминками. В ее аромате слышатся тонкие нотки сливок, ванили и сухофруктов, во вкусе чувствуется нежная ванильная сладость и приятная молочная кислинка в послевкусии. Отлично подходит для приготовления вкусных сырников!',
    price: 109,
    cents: 90,
    image: milk15,
    country: "Россия",
    calories: 344,
    proteins: 7.7,
    fats: 20.7,
    carbohydrates: 31.6,
    category: "milk",
    subcategories: "mass",
    type: "nopopular",
  },
  {
    id: 21,
    name: "Яйцо куриное Деревенские напевы Отборное фасованное 10шт",
    brend: "Деревенские Напевы",
    description:
      'Яйцо куриное "Деревенские напевы" отборное - контейнер с одним десятком яиц. Каждое яйцо отборной категории имеет вес 65–75 г. Перед употреблением куриное яйцо следует промыть под проточной водой, а далее использовать по назначению: сварить, сделать яичницу или омлет, использовать для приготовления выпечки и пр.',
    price: 114,
    cents: 90,
    image: milk16,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 22,
    name: "Яйца куриные Роскар Экстра категория С0 10шт",
    brend: "Роскар",
    description:
      "Яйца Роскар Экстра СО - это крупные яйца отборной категории с ярким оранжевым желтком, прочной и чистой скорлупой. Благодаря здоровому питанию кур-несушек, в них содержится много каротиноидов, витаминов и минеральных веществ, которые хорошо усваиваются человеческим организмом.",
    price: 139,
    cents: 90,
    image: milk17,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 23,
    name: "Яйцо куриное Окское отборное С0 10шт",
    brend: "Окское",
    description:
      "Продукт отборной категории от крупнейшего птицеводческого предприятия Рязанской области. Весь процесс производства соответствует передовым международным стандартам. Качество и санитарная безопасность соответствуют ГОСТ. Яйца получены от кур, выращенных на натуральных кормах.",
    price: 139,
    cents: 90,
    image: milk18,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 24,
    name: "Масло сливочное Вкуснотеево Традиционное 82,5% 200г",
    brend: "Вкуснотеево",
    description:
      'Масло сливочное "Вкуснотеево" 82,5% изготовлено по особой технологии – способом холодного сбивания. Благодаря такому способу сливки не нагреваются и в них не разрушаются белковые связи. Так в масле сохраняется чистый, насыщенный вкус натуральных сливок.',
    price: 279,
    cents: 90,
    image: milk19,
    country: "Россия",
    calories: 748,
    proteins: 0.6,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 25,
    name: "Масло сливочное Вкуснотеево Традиционное 82,5% г",
    brend: "Вкуснотеево",
    description:
      "Масло сливочное высшего сорта Вкуснотеево «Традиционное» 82,5% изготовлено по особой технологии – способом холодного сбивания. Благодаря такому способу сливки не нагреваются и в них не разрушаются белковые связи. Так в масле сохраняется чистый, насыщенный вкус натуральных сливок. Для изготовления 1 кг масла используется 25 л молока высшего сорта! Особая форма «буханки» удобна в приготовлении бутербродов и позволяет воплотить больше идей при сервировке. Масло упаковано в линкавер – полимерную бумагу, что позволяет увеличить срок хранения продукта вдвое, до 60 суток.",
    price: 359,
    cents: 90,
    image: milk20,
    country: "Россия",
    calories: 748,
    proteins: 1,
    fats: 82,
    carbohydrates: 1,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 26,
    name: "Сливочное масло Экомилк ГОСТ 82,5% высший сорт 180г",
    brend: "Экомилк",
    description:
      'Сливочное масло с бархатным вкусом и тонким ароматом натуральных сливок. Идеально для любых блюд, но в особенности для десертов: попробуйте приготовить классический масляный крем для тортов и капкейков! "Экомилк" — компания, которая славится своим сливочным маслом. Исключительно натуральное масло производится на самом эффективном и технологичном оборудовании европейского уровня. Благодаря собственной эколаборатории качество "Экомилк" стабильно высокое',
    price: 219,
    cents: 90,
    image: milk21,
    country: "Россия",
    calories: 748,
    proteins: 0.6,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 27,
    name: "Майонез Слобода Оливковый 67% 800мл",
    brend: "Слобода",
    description:
      'Оливковый майонез отличается ярким натуральным вкусом с изысканной терпкой ноткой. Соус отлично подойдет для любых блюд: смело экспериментируйте, потому что результат всегда будет на высоте! Майонез "Слобода" — это исключительно натуральные ингредиенты. Свежие яичные желтки, масло из отборных испанских оливок, никаких искусственных добавок — секрет вкуса майонеза "Слобода".',
    price: 179,
    cents: 90,
    image: milk22,
    country: "Россия",
    calories: 627,
    proteins: 3,
    fats: 67,
    carbohydrates: 2.8,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 28,
    name: "Майонез Mr. Ricco Провансаль 67% 340г",
    brend: "Mr.Ricco",
    description:
      "Mr.Ricco Провансаль - это майонез, обладающий традиционным вкусом и приготовленный по классической рецептуре, с большим содержанием растительного масла и горчицы. Сохраняя для Вас тот самый вкус Провансаль, технологи Mr.Ricco при этом создали полностью натуральный майонез без добавления каких-либо искусственных и вредных для организма компонентов. Mr.Ricco.",
    price: 89,
    cents: 99,
    image: milk23,
    country: "Россия",
    calories: 610,
    proteins: 0.3,
    fats: 67,
    carbohydrates: 2.5,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 29,
    name: "Майонез Слобода Оливковый 67% 230мл",
    brend: "Слобода",
    description:
      'Оливковый майонез отличается ярким натуральным вкусом с изысканной терпкой ноткой. Соус отлично подойдет для любых блюд: смело экспериментируйте, потому что результат всегда будет на высоте! Майонез "Слобода" — это исключительно натуральные ингредиенты. Свежие яичные желтки, масло из отборных испанских оливок, никаких искусственных добавок — секрет вкуса майонеза "Слобода".',
    price: 62,
    cents: 90,
    image: milk24,
    country: "Россия",
    calories: 627,
    proteins: 3,
    fats: 67,
    carbohydrates: 2.8,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 30,
    name: "Майонез Mr. Ricco Провансаль 67% 840г",
    brend: "Mr.Ricco",
    description:
      "Mr.Ricco Провансаль - это майонез, обладающий традиционным вкусом и приготовленный по классической рецептуре, с большим содержанием растительного масла и горчицы. Сохраняя для Вас тот самый вкус Провансаль, технологи Mr.Ricco при этом создали полностью натуральный майонез без добавления каких-либо искусственных и вредных для организма компонентов. Mr.Ricco.",
    price: 241,
    cents: 90,
    image: milk25,
    country: "Россия",
    calories: 610,
    proteins: 0.4,
    fats: 67,
    carbohydrates: 2,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 31,
    name: "Йогурт питьевой Epica Киви-Виноград 2,5% 260г",
    brend: "EPICA",
    description:
      "Мы вдохновляемся природой, нашей командой и вами. Стараемся замечать необычное в привычном и превращать это в новую EPICA. Изобретать йогурт заново и всегда делать его по-своему.",
    price: 69,
    cents: 99,
    image: milk26,
    country: "Россия",
    calories: 85,
    proteins: 4,
    fats: 2.5,
    carbohydrates: 11.9,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 32,
    name: "Мороженое 48 копеек Сливочное шоколадное 210г",
    brend: "48 копеек",
    description:
      "Натуральное молоко, свежие сливки и много-много шоколада. Мороженое 48 Копеек — современный взгляд на шоколадное лакомство.",
    price: 169,
    cents: 90,
    image: milk27,
    country: "Россия",
    calories: 189,
    proteins: 3.6,
    fats: 8.7,
    carbohydrates: 24,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 33,
    name: "Мороженое Коровка из Кореновки Пломбир ванильный 15%, 100г",
    brend: "Коровка из Кореновки",
    description:
      "Пломбир Коровка из Кореновки – традиционное сливочное мороженое в хрустящем вафельном стаканчике. Это лакомство понравится всем без исключения благодаря своему нежному сливочно-кремовому вкусу. Продукт изготовлен по оригинальной рецептуре на основе только экологичных и безопасных ингредиентов. Пломбир сделан из натурального молока и сливок, не содержит искусственных консервантов, ароматизаторов и красителей. Герметичная упаковка удобна для транспортировки и хранения, а также очень гигиенична.",
    price: 79,
    cents: 99,
    image: milk28,
    country: "Россия",
    calories: 216,
    proteins: 3,
    fats: 14,
    carbohydrates: 19,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 34,
    name: "Мороженое 48 копеек Пломбир брикет 210г",
    brend: "48 копеек",
    description:
      "Натуральное молоко, свежие сливки и много-много шоколада. Мороженое 48 Копеек — современный взгляд на шоколадное лакомство.",
    price: 169,
    cents: 90,
    image: milk29,
    country: "Россия",
    calories: 221,
    proteins: 2.7,
    fats: 13.5,
    carbohydrates: 22.1,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 35,
    name: "Мороженое 48 копеек Манго со сливками 241г",
    brend: "48 копеек",
    description:
      "Натуральное молоко, свежие сливки и много-много шоколада. Мороженое 48 Копеек — современный взгляд на шоколадное лакомство.",
    price: 169,
    cents: 90,
    image: milk31,
    country: "Россия",
    calories: 178,
    proteins: 1.6,
    fats: 6.4,
    carbohydrates: 28.6,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 36,
    name: "Мороженое Коровка из Кореновки Рожок со сгущенным молоком 120г",
    brend: "Коровка из Кореновки",
    description:
      "Мы стараемся для вас, для того чтобы любой продукт Коровка из Кореновки приносил радость в вашу жизнь и жизнь ваших близких.",
    price: 167,
    cents: 90,
    image: milk32,
    country: "Россия",
    calories: 259,
    proteins: 3.4,
    fats: 15.5,
    carbohydrates: 27.5,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
];
