import meat1 from "../images/products/meat1.webp";
import meat2 from "../images/products/meat-2.webp";
import meat3 from "../images/products/meat-3.webp";
import meat4 from "../images/products/meat-4.webp";
import meat5 from "../images/products/meat-5.webp";
import milk1 from "../images/products/milk-1.webp";
import milk2 from "../images/products/milk-2.webp";
import milk3 from "../images/products/milk-3.webp";
import milk4 from "../images/products/milk-4.webp";
import milk5 from "../images/products/milk-5.webp";
import milk6 from "../images/products/milk6.jpeg";
import milk7 from "../images/products/milk7.jpeg";
import milk8 from "../images/products/milk8.jpeg";
import milk9 from "../images/products/milk9.jpeg";
import milk10 from "../images/products/milk10.jpeg";
import milk11 from "../images/products/milk11.jpeg";
import milk12 from "../images/products/milk12.jpeg";
import milk13 from "../images/products/milk13.png";
import milk14 from "../images/products/milk14.jpeg";
import milk15 from "../images/products/milk15.jpeg";
import milk16 from "../images/products/milk16.jpeg";
import milk17 from "../images/products/milk17.jpeg";
import milk18 from "../images/products/milk18.jpeg";
import milk19 from "../images/products/milk19.jpeg";
import milk20 from "../images/products/milk20.jpeg";
import milk21 from "../images/products/milk21.jpeg";
import milk22 from "../images/products/milk22.jpeg";
import milk23 from "../images/products/milk23.jpeg";
import milk24 from "../images/products/milk24.jpeg";
import milk25 from "../images/products/milk25.jpeg";
import milk26 from "../images/products/milk26.jpeg";
import milk27 from "../images/products/milk27.jpeg";
import milk28 from "../images/products/milk28.jpeg";
import milk29 from "../images/products/milk29.jpeg";
import milk31 from "../images/products/milk31.jpeg";
import milk32 from "../images/products/milk32.jpeg";
import meat6 from "../images/products/meat6.jpeg";
import meat7 from "../images/products/meat7.jpeg";
import meat8 from "../images/products/meat8.jpeg";
import meat9 from "../images/products/meat9.jpeg";
import meat11 from "../images/products/meat11.jpeg";
import meat12 from "../images/products/meat12.jpeg";
import meat13 from "../images/products/meat13.jpeg";
import meat14 from "../images/products/meat14.jpeg";
import meat15 from "../images/products/meat15.jpeg";
import meat16 from "../images/products/meat16.jpeg";
import meat17 from "../images/products/meat17.jpeg";
import meat18 from "../images/products/meat18.webp";
import meat19 from "../images/products/meat19.webp";
import meat20 from "../images/products/meat20.webp";
import meat21 from "../images/products/meat21.webp";
import fruit1 from "../images/products/fruit1.webp";
import fruit2 from "../images/products/fruits2.webp";
import fruit3 from "../images/products/fruit3.webp";
import fruit4 from "../images/products/fruit4.webp";
import fruit5 from "../images/products/fruit5.webp";
import fruit6 from "../images/products/fruit6.webp";
import fruit7 from "../images/products/fruit7.webp";
import fruit8 from "../images/products/fruit8.webp";
import fruit9 from "../images/products/fruit9.webp";
import fruit10 from "../images/products/fruit10.webp";
import fruit11 from "../images/products/fruit11.webp";
import fruit12 from "../images/products/fruit12.webp";
import fruit13 from "../images/products/fruit13.webp";
import fruit14 from "../images/products/fruit14.webp";
import fruit15 from "../images/products/fruit15.webp";
import fruit16 from "../images/products/fruit16.webp";
import fruit17 from "../images/products/fruit17.webp";
import fruit18 from "../images/products/fruit18.webp";
import fruit19 from "../images/products/fruit19.webp";
import fruit20 from "../images/products/fruit20.webp";

export const ProductsList = [
  {
    id: 1,
    name: "Фарш Ближние горки деревенский охлажденный 400г",
    brend: "Ближние Горки",
    description:
      "Фарш «Деревенский» содержит много питательных веществ, поэтому любое кулинарное изделие, приготовленное из него, будет не только вкусным, но и полезным. Этот полуфабрикат бренда «Ближние Горки» из свинины и говядины высшего сорта. Из него можно сделать сотню праздничных блюд и обедов на каждый день. Это сочное и ароматное мясо подходит для приготовления котлет, рулетов, мясных запеканок, бифштексов и пирожков.",
    price: 149,
    cents: 90,
    image: meat1,
    country: "Россия",
    calories: 418,
    proteins: 10,
    fats: 42,
    carbohydrates: 0,
    category: "meat",
    subcategories: "groundmeat",
    type: "popular",
  },
  {
    id: 2,
    name: "Бедро цыпленка-бройлера Петелинка в упаковке",
    brend: "Петелинка",
    description:
      "Бедро Особое Петелинка - часть тушки с сочным и вкусным мясом. Куриные бедра содержат много полезных веществ. Существует большое количество рецептов из этого продукта, а приготовление займет минимальное количество времени. Петелинка – это чистый продукт без вредных добавок, ГМО и гормонов роста. Гарантия всегда свежего продукта.",
    price: 319,
    cents: 90,
    image: meat2,
    country: "Россия",
    calories: 190,
    proteins: 17,
    fats: 13,
    carbohydrates: 0,
    category: "meat",
    subcategories: "bird",
    type: "popular",
  },
  {
    id: 3,
    name: "Мини-котлетки куриные Мираторг с моцареллой 380г",
    brend: "Мираторг",
    description:
      "Отлично сочетается с куриным мясом, придает ему нежный вкус и аромат. Во время приготовления начинка пропитывает мясо и придаёт ему насыщенный вкус и аромат. А хрустящая сухарная панировка сдерживает весь сок внутри. Обжарьте котлеты с двух сторон до золотистой корочки, убавьте огонь и доведите до готовности под крышкой.",
    price: 159,
    cents: 90,
    image: meat3,
    country: "Россия",
    calories: 258,
    proteins: 9,
    fats: 14,
    carbohydrates: 24,
    category: "meat",
    subcategories: "cutlet",
    type: "popular",
  },
  {
    id: 4,
    name: "Чевапчичи Слово мясника охлажденные 300г",
    brend: "Слово Мясника",
    description:
      "Чевапчичи из свинины и говядины рубленые от бренда СЛОВО МЯСНИКА – вкусный полуфабрикат. Ароматные колбаски из рубленой свинины и говядины с луком и специями внесут разнообразие в меню любимых блюд для гриля. А если вы решили остаться дома, приготовьте чевапчичи в духовке. Попробуйте пряные чевапчичи – традиционное блюдо балканской кухни.",
    price: 119,
    cents: 90,
    image: meat4,
    country: "Россия",
    calories: 360,
    proteins: 12,
    fats: 35,
    carbohydrates: 0,
    category: "meat",
    subcategories: "bird",
    type: "popular",
  },
  {
    id: 5,
    name: "Ребрышки свиные Черкизово Аппетитные в маринаде",
    brend: "Черкизово",
    description:
      "Ребрышки аппетитные в маринаде достойны своего названия. Мясо получается необыкновенно сочным, а благодаря особым приправам - пряным и ароматным. И что немаловажно, его легко приготовить. Вам лишь надо удалить этикетку, сделать небольшое надрез в верхней части пакета, уложить пакет на холодный противень и поставить в разогретую духовку.",
    price: 369,
    cents: 90,
    image: meat5,
    country: "Россия",
    calories: 292,
    proteins: 19,
    fats: 20,
    carbohydrates: 2,
    category: "meat",
    subcategories: "pork",
    type: "popular",
  },
  {
    id: 6,
    name: "Молоко Простоквашино пастеризованное 2,5% 930мл",
    brend: "Простоквашино",
    description:
      "Молоко Простоквашино отлично дополнит ваш завтрак, его можно добавить в кофе или чай или выпить на ночь. Кроме того, оно отлично подойдет для готовки блинчиков, каш и множества других любимых домашних блюд. Пейте Молоко Простоквашино с удовольствием!",
    price: 81,
    cents: 99,
    image: milk1,
    country: "Россия",
    calories: 53,
    proteins: 3,
    fats: 2.5,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 7,
    name: "Молоко ультрапастеризованное Домик в деревне 3,2% 950г",
    brend: "Домик в деревне",
    description:
      "Молоко «Домик в деревне» – 100% натуральный продукт, приготовленный по традиционным рецептам. «Домик в деревне» - все, что мы узнали о натуральности, мы узнали от бабушек. 100% натуральное молоко. Без добавления консервантов и красителей. Жирность 3,2% подходит для тех, кто любит традиционный вкус молока. Пить молоко «Домик в деревне» можно холодным и тёплым. Идеально для кофе, чая и приготовления ваших любимых блюд.",
    price: 108,
    cents: 90,
    image: milk2,
    country: "Россия",
    calories: 60,
    proteins: 3.1,
    fats: 3.2,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 8,
    name: "Молоко Село Зеленое ультрапастеризованное 3,2, 950мл",
    brend: "Село Зеленое",
    description:
      "Молоко «Село Зелёное» 3,2% – полезный для здоровья натуральный и экологичный продукт высшего качества. Высококачественное сырье, новейшие технологии обработки и современные упаковочные решения позволяют надолго сохранять натуральный продукт без использования консервантов.",
    price: 99,
    cents: 99,
    image: milk3,
    country: "Россия",
    calories: 60,
    proteins: 3,
    fats: 3.2,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 9,
    name: "Молоко ультрапастеризованное 2,5% в ассортименте 924мл/1000мл",
    brend: "Молоко ультрапастеризованное",
    description:
      "Молоко содержит целое множество полезностей для поддержания вашего организма в превосходном состоянии.",
    price: 96,
    cents: 99,
    image: milk4,
    country: "Россия",
    calories: 53.3,
    proteins: 2.5,
    fats: 3,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 10,
    name: "Молоко Хуторок 1,5% 900мл",
    brend: "Хуторок",
    description:
      "Свежее и настоящее молоко, созданное с любовью к родным и близким.",
    price: 69,
    cents: 99,
    image: milk5,
    country: "Россия",
    calories: 44,
    proteins: 3,
    fats: 1.5,
    carbohydrates: 4.7,
    category: "milk",
    subcategories: "milk1",
    type: "popular",
  },
  {
    id: 11,
    name: "Яйцо куриное столовое 1 категория в ассортименте 10шт",
    brend: "Тендер",
    description:
      "Только свежее и отборное яйцо. Мы используем современные технологии изготовления кормов, которые позволяют сохранить в них все необходимые питательные вещества и витамины.",
    price: 36,
    cents: 49,
    image: milk6,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 12,
    name: "Яйцо куриное Деревенские напевы 1 категории 10шт",
    brend: "Деревенские Напевы",
    description:
      'Яйцо куриное "Деревенские напевы" 1 категория - контейнер с одним десятком яиц первой категории. Каждое яйцо имеет вес 55–65 г.',
    price: 99,
    cents: 99,
    image: milk7,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 13,
    name: "Майонез Московский Провансаль Классический 67% 700мл",
    brend: "Московский провансаль",
    description:
      "Майонез Я ЛЮБЛЮ ГОТОВИТЬ Московский провансаль Классический 67% изготовлен из семи натуральных ингредиентов. Не содержит ГМО, красителей и консервантов.",
    price: 149,
    cents: 90,
    image: milk8,
    country: "Россия",
    calories: 619,
    proteins: 0.4,
    fats: 67,
    carbohydrates: 2.2,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 14,
    name: "Творог Хуторок 5% 180г",
    brend: "Хуторог",
    description:
      'Нежная творожная консистенция, легкая кислинка во вкусе. Творог "Хуторок" 5% идеально подходит для приготовления сырников и запеканок!',
    price: 69,
    cents: 99,
    image: milk9,
    country: "Россия",
    calories: 121,
    proteins: 16,
    fats: 5,
    carbohydrates: 3,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 15,
    name: "Йогурт греческий Teos Натуральный 2% 140г",
    brend: "Савушкин",
    description:
      'Йогурт "Teos" изготавливается по традиционной технологии процеживания, благодаря чему содержит в 2 раза больше белка в сравнении с классическими йогуртами и имеет невероятно густую, кремовую консистенцию.',
    price: 54,
    cents: 99,
    image: milk10,
    country: "Россия",
    calories: 62.8,
    proteins: 7,
    fats: 2,
    carbohydrates: 4.2,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 16,
    name: "Творог Хуторок 9% 300г",
    brend: "Хуторок",
    description:
      "Продукт обладает чистым выраженным кисломолочным вкусом, привлекательным ароматом и приятной консистенцией. Отлично подходит для завтраков, полезных перекусов.",
    price: 129,
    cents: 90,
    image: milk11,
    country: "Россия",
    calories: 157,
    proteins: 16,
    fats: 9,
    carbohydrates: 3,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 17,
    name: "Творог Хуторок 5% 300г",
    brend: "Хуторок",
    description:
      "Продукт обладает чистым выраженным кисломолочным вкусом, привлекательным ароматом и приятной консистенцией. Отлично подходит для завтраков, полезных перекусов.",
    price: 109,
    cents: 90,
    image: milk12,
    country: "Россия",
    calories: 121,
    proteins: 16,
    fats: 5,
    carbohydrates: 3,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 18,
    name: "Масло Экомилк Традиционное сливочное 82,5% 160г",
    brend: "Экомилк",
    description:
      "Масло сливочное Экомилк - продукт высшего сорта, изготовленный по традиционной рецептуре. Сырье для производства соответствует принятым современным нормам качества. Масло обладает ярким, насыщенным сливочным вкусом и оптимально подходит для заправки каш, спагетти и картофельного пюре.",
    price: 109,
    cents: 90,
    image: milk13,
    country: "Россия",
    calories: 748,
    proteins: 0.6,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 19,
    name: "Масло Брест-Литовск сливочное 82,5% 180г",
    brend: "Брест-Литовск",
    description:
      'Это масло готовится из свежих сливок: оцените его нежный вкус! Универсальное масло подойдет для любых блюд. Добавляйте в кашу, готовьте сэндвичи и канапе, смело используйте для выпечки - каждый рецепт станет удачным. "Брест-Литовск" - натуральные молочные продукты, которые готовятся по классическим рецептам. Благодаря сочетанию традиций и современных технологий белорусскому производителю удается радовать покупателя неизменным качеством из года в год.',
    price: 229,
    cents: 90,
    image: milk14,
    country: "Россия",
    calories: 747,
    proteins: 0.5,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 20,
    name: "Масса творожная РостАгроЭкспорт Особая с изюмом 180г",
    brend: "РостАгроЭкспорт",
    description:
      'Масса творожная "Особая с сахаром и изюмом" - это молочный продукт, который готовится без добавления консервантов и красителей. В состав творожного десерта входят исключительно натуральные ингредиенты. Цвет творожной массы приятный, нежно-бежевый, консистенция - рассыпчатая и однородная, с цельными изюминками. В ее аромате слышатся тонкие нотки сливок, ванили и сухофруктов, во вкусе чувствуется нежная ванильная сладость и приятная молочная кислинка в послевкусии. Отлично подходит для приготовления вкусных сырников!',
    price: 109,
    cents: 90,
    image: milk15,
    country: "Россия",
    calories: 344,
    proteins: 7.7,
    fats: 20.7,
    carbohydrates: 31.6,
    category: "milk",
    subcategories: "mass",
    type: "nopopular",
  },
  {
    id: 21,
    name: "Яйцо куриное Деревенские напевы Отборное фасованное 10шт",
    brend: "Деревенские Напевы",
    description:
      'Яйцо куриное "Деревенские напевы" отборное - контейнер с одним десятком яиц. Каждое яйцо отборной категории имеет вес 65–75 г. Перед употреблением куриное яйцо следует промыть под проточной водой, а далее использовать по назначению: сварить, сделать яичницу или омлет, использовать для приготовления выпечки и пр.',
    price: 114,
    cents: 90,
    image: milk16,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 22,
    name: "Яйца куриные Роскар Экстра категория С0 10шт",
    brend: "Роскар",
    description:
      "Яйца Роскар Экстра СО - это крупные яйца отборной категории с ярким оранжевым желтком, прочной и чистой скорлупой. Благодаря здоровому питанию кур-несушек, в них содержится много каротиноидов, витаминов и минеральных веществ, которые хорошо усваиваются человеческим организмом.",
    price: 139,
    cents: 90,
    image: milk17,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 23,
    name: "Яйцо куриное Окское отборное С0 10шт",
    brend: "Окское",
    description:
      "Продукт отборной категории от крупнейшего птицеводческого предприятия Рязанской области. Весь процесс производства соответствует передовым международным стандартам. Качество и санитарная безопасность соответствуют ГОСТ. Яйца получены от кур, выращенных на натуральных кормах.",
    price: 139,
    cents: 90,
    image: milk18,
    country: "Россия",
    calories: 157,
    proteins: 12.7,
    fats: 11.5,
    carbohydrates: 0.7,
    category: "milk",
    subcategories: "Eggs",
    type: "nopopular",
  },
  {
    id: 24,
    name: "Масло сливочное Вкуснотеево Традиционное 82,5% 200г",
    brend: "Вкуснотеево",
    description:
      'Масло сливочное "Вкуснотеево" 82,5% изготовлено по особой технологии – способом холодного сбивания. Благодаря такому способу сливки не нагреваются и в них не разрушаются белковые связи. Так в масле сохраняется чистый, насыщенный вкус натуральных сливок.',
    price: 279,
    cents: 90,
    image: milk19,
    country: "Россия",
    calories: 748,
    proteins: 0.6,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 25,
    name: "Масло сливочное Вкуснотеево Традиционное 82,5% г",
    brend: "Вкуснотеево",
    description:
      "Масло сливочное высшего сорта Вкуснотеево «Традиционное» 82,5% изготовлено по особой технологии – способом холодного сбивания. Благодаря такому способу сливки не нагреваются и в них не разрушаются белковые связи. Так в масле сохраняется чистый, насыщенный вкус натуральных сливок. Для изготовления 1 кг масла используется 25 л молока высшего сорта! Особая форма «буханки» удобна в приготовлении бутербродов и позволяет воплотить больше идей при сервировке. Масло упаковано в линкавер – полимерную бумагу, что позволяет увеличить срок хранения продукта вдвое, до 60 суток.",
    price: 359,
    cents: 90,
    image: milk20,
    country: "Россия",
    calories: 748,
    proteins: 1,
    fats: 82,
    carbohydrates: 1,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 26,
    name: "Сливочное масло Экомилк ГОСТ 82,5% высший сорт 180г",
    brend: "Экомилк",
    description:
      'Сливочное масло с бархатным вкусом и тонким ароматом натуральных сливок. Идеально для любых блюд, но в особенности для десертов: попробуйте приготовить классический масляный крем для тортов и капкейков! "Экомилк" — компания, которая славится своим сливочным маслом. Исключительно натуральное масло производится на самом эффективном и технологичном оборудовании европейского уровня. Благодаря собственной эколаборатории качество "Экомилк" стабильно высокое',
    price: 219,
    cents: 90,
    image: milk21,
    country: "Россия",
    calories: 748,
    proteins: 0.6,
    fats: 82.5,
    carbohydrates: 0.8,
    category: "milk",
    subcategories: "oil",
    type: "nopopular",
  },
  {
    id: 27,
    name: "Майонез Слобода Оливковый 67% 800мл",
    brend: "Слобода",
    description:
      'Оливковый майонез отличается ярким натуральным вкусом с изысканной терпкой ноткой. Соус отлично подойдет для любых блюд: смело экспериментируйте, потому что результат всегда будет на высоте! Майонез "Слобода" — это исключительно натуральные ингредиенты. Свежие яичные желтки, масло из отборных испанских оливок, никаких искусственных добавок — секрет вкуса майонеза "Слобода".',
    price: 179,
    cents: 90,
    image: milk22,
    country: "Россия",
    calories: 627,
    proteins: 3,
    fats: 67,
    carbohydrates: 2.8,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 28,
    name: "Майонез Mr. Ricco Провансаль 67% 340г",
    brend: "Mr.Ricco",
    description:
      "Mr.Ricco Провансаль - это майонез, обладающий традиционным вкусом и приготовленный по классической рецептуре, с большим содержанием растительного масла и горчицы. Сохраняя для Вас тот самый вкус Провансаль, технологи Mr.Ricco при этом создали полностью натуральный майонез без добавления каких-либо искусственных и вредных для организма компонентов. Mr.Ricco.",
    price: 89,
    cents: 99,
    image: milk23,
    country: "Россия",
    calories: 610,
    proteins: 0.3,
    fats: 67,
    carbohydrates: 2.5,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 29,
    name: "Майонез Слобода Оливковый 67% 230мл",
    brend: "Слобода",
    description:
      'Оливковый майонез отличается ярким натуральным вкусом с изысканной терпкой ноткой. Соус отлично подойдет для любых блюд: смело экспериментируйте, потому что результат всегда будет на высоте! Майонез "Слобода" — это исключительно натуральные ингредиенты. Свежие яичные желтки, масло из отборных испанских оливок, никаких искусственных добавок — секрет вкуса майонеза "Слобода".',
    price: 62,
    cents: 90,
    image: milk24,
    country: "Россия",
    calories: 627,
    proteins: 3,
    fats: 67,
    carbohydrates: 2.8,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 30,
    name: "Майонез Mr. Ricco Провансаль 67% 840г",
    brend: "Mr.Ricco",
    description:
      "Mr.Ricco Провансаль - это майонез, обладающий традиционным вкусом и приготовленный по классической рецептуре, с большим содержанием растительного масла и горчицы. Сохраняя для Вас тот самый вкус Провансаль, технологи Mr.Ricco при этом создали полностью натуральный майонез без добавления каких-либо искусственных и вредных для организма компонентов. Mr.Ricco.",
    price: 241,
    cents: 90,
    image: milk25,
    country: "Россия",
    calories: 610,
    proteins: 0.4,
    fats: 67,
    carbohydrates: 2,
    category: "milk",
    subcategories: "Sauces",
    type: "nopopular",
  },
  {
    id: 31,
    name: "Йогурт питьевой Epica Киви-Виноград 2,5% 260г",
    brend: "EPICA",
    description:
      "Мы вдохновляемся природой, нашей командой и вами. Стараемся замечать необычное в привычном и превращать это в новую EPICA. Изобретать йогурт заново и всегда делать его по-своему.",
    price: 69,
    cents: 99,
    image: milk26,
    country: "Россия",
    calories: 85,
    proteins: 4,
    fats: 2.5,
    carbohydrates: 11.9,
    category: "milk",
    subcategories: "Dairy",
    type: "nopopular",
  },
  {
    id: 32,
    name: "Мороженое 48 копеек Сливочное шоколадное 210г",
    brend: "48 копеек",
    description:
      "Натуральное молоко, свежие сливки и много-много шоколада. Мороженое 48 Копеек — современный взгляд на шоколадное лакомство.",
    price: 169,
    cents: 90,
    image: milk27,
    country: "Россия",
    calories: 189,
    proteins: 3.6,
    fats: 8.7,
    carbohydrates: 24,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 33,
    name: "Мороженое Коровка из Кореновки Пломбир ванильный 15%, 100г",
    brend: "Коровка из Кореновки",
    description:
      "Пломбир Коровка из Кореновки – традиционное сливочное мороженое в хрустящем вафельном стаканчике. Это лакомство понравится всем без исключения благодаря своему нежному сливочно-кремовому вкусу. Продукт изготовлен по оригинальной рецептуре на основе только экологичных и безопасных ингредиентов. Пломбир сделан из натурального молока и сливок, не содержит искусственных консервантов, ароматизаторов и красителей. Герметичная упаковка удобна для транспортировки и хранения, а также очень гигиенична.",
    price: 79,
    cents: 99,
    image: milk28,
    country: "Россия",
    calories: 216,
    proteins: 3,
    fats: 14,
    carbohydrates: 19,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 34,
    name: "Мороженое 48 копеек Пломбир брикет 210г",
    brend: "48 копеек",
    description:
      "Натуральное молоко, свежие сливки и много-много шоколада. Мороженое 48 Копеек — современный взгляд на шоколадное лакомство.",
    price: 169,
    cents: 90,
    image: milk29,
    country: "Россия",
    calories: 221,
    proteins: 2.7,
    fats: 13.5,
    carbohydrates: 22.1,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 35,
    name: "Мороженое 48 копеек Манго со сливками 241г",
    brend: "48 копеек",
    description:
      "Натуральное молоко, свежие сливки и много-много шоколада. Мороженое 48 Копеек — современный взгляд на шоколадное лакомство.",
    price: 169,
    cents: 90,
    image: milk31,
    country: "Россия",
    calories: 178,
    proteins: 1.6,
    fats: 6.4,
    carbohydrates: 28.6,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 36,
    name: "Мороженое Коровка из Кореновки Рожок со сгущенным молоком 120г",
    brend: "Коровка из Кореновки",
    description:
      "Мы стараемся для вас, для того чтобы любой продукт Коровка из Кореновки приносил радость в вашу жизнь и жизнь ваших близких.",
    price: 167,
    cents: 90,
    image: milk32,
    country: "Россия",
    calories: 259,
    proteins: 3.4,
    fats: 15.5,
    carbohydrates: 27.5,
    category: "milk",
    subcategories: "icecream",
    type: "nopopular",
  },
  {
    id: 37,
    name: "Колбаски Мираторг Немецкие охлажденные 400г",
    brend: "Мираторг",
    description:
      "Попробуйте новинку из отборной свинины! Приготовленные по классическому баварскому рецепту, наши колбаски прекрасно подходят и для варки, и для жарки, особенно на углях. Чтобы вкус мяса раскрылся полностью, а натуральная черева приобрела приятный оттенок, рекомендуем закинуть колбаски в кипящую воду на 1-2 минуты, а затем обжарить. Приятного аппетита или, как говорят в Баварии, Guten Appetit!",
    price: 167,
    cents: 90,
    image: meat6,
    country: "Россия",
    calories: 330,
    proteins: 10,
    fats: 32,
    carbohydrates: 0,
    category: "meat",
    subcategories: "pork",
    type: "nopopular",
  },

  {
    id: 38,
    name: "Бедро куриное Петелинка бескостное без кожи охлажденное",
    brend: "Петелинка",
    description:
      "Филе бедра Петелинка куриное без кожи – вкусное, нежное, сочное мясо, очищенное от косточек и кожи. Прекрасно подходит для запекания в духовке, жарки на сковороде, приготовления на гриле или мангале. Служит ценным источником витаминов, микроэлементов и белка. Для производства используется мясо птицы, выращенной на птицеферме в комфортных условиях. Цыплята с рождения живут в специальных ангарах, где могут свободно перемещаться. Натуральный зерновой откорм, современные технологии переработки и тщательный контроль на всех этапах производства позволяют выпускать высококачественную и безопасную продукцию. Продукт не содержит ГМО, гормонов роста и антибиотиков. Охлажденное филе упаковано в лоток.",
    price: 535,
    cents: 90,
    image: meat7,
    country: "Россия",
    calories: 180,
    proteins: 18,
    fats: 12,
    carbohydrates: 0,
    category: "meat",
    subcategories: "bird",
    type: "nopopular",
  },
  {
    id: 39,
    name: "Свинина Черкизово По-дижонски охлажденная 700г",
    brend: "Петелинка",
    description:
      "Охлажденная сочная лопатка для запекания в маринаде из французской горчицы. Горчица способствует удержанию влаги в мясе , в результате мясо еще больше сохраняет свою сочность, что делает деликатес аппетитным, нежным и мягким.",
    price: 289,
    cents: 90,
    image: meat8,
    country: "Россия",
    calories: 183,
    proteins: 12,
    fats: 15,
    carbohydrates: 0,
    category: "meat",
    subcategories: "pork",
    type: "nopopular",
  },
  {
    id: 40,
    name: "Гуляш из свинины Слово мясника охлажденный 400г",
    brend: "Слово мясника",
    description:
      "Аккуратные кубики из свиной лопатки 3 х 3 см. Из нежных кусочков мяса рекомендуется готовить сытные вторые блюда.",
    price: 179,
    cents: 90,
    image: meat9,
    country: "Россия",
    calories: 170,
    proteins: 16,
    fats: 12,
    carbohydrates: 0,
    category: "meat",
    subcategories: "pork",
    type: "nopopular",
  },
  {
    id: 41,
    name: "Вырезка свиная охлажденная в ассортименте",
    brend: "Слово мясника",
    description:
      "Нежное, полезное и низкокалорийное мясо — свиная вырезка без костей станет идеальной основой для множества любимых блюд. Подойдет для запекания на мангале, а также в духовке, целиком или порционно.",
    price: 499,
    cents: 90,
    image: meat11,
    country: "Россия",
    calories: 150,
    proteins: 16,
    fats: 10,
    carbohydrates: 0,
    category: "meat",
    subcategories: "pork",
    type: "nopopular",
  },
  {
    id: 42,
    name: "Котлеты Троекурово Деревенские куриные охлажденные 400г",
    brend: "Троекурово",
    description:
      "Котлеты куриные Троекурово Деревенские 400г - это охлажденный полуфабрикат, приготовленный по фирменному рецепту из рубленого филе цыпленка-бройлера. Вкусные и аппетитные котлетки без панировки очень похожи на домашние; они такие же сочные, нежные, с натуральным вкусом отборного куриного мяса. Их можно приготовить двумя способами: запечь в разогретой до 150-200°С духовке в течение 10-15 минут или обжарить на раскаленной сковороде (сначала на сильном огне, а затем под крышкой на медленном). Продукция торговой марки Троекурово производится из птицы, выращенной на отечественном корме без ГМО и гормонов роста, что позволяет сохранить натуральный вкус и максимум питательной ценности куриного мяса.",
    price: 129,
    cents: 90,
    image: meat12,
    country: "Россия",
    calories: 190,
    proteins: 17,
    fats: 12,
    carbohydrates: 4,
    category: "meat",
    subcategories: "bird",
    type: "nopopular",
  },
  {
    id: 43,
    name: "Филе цыпленка-бройлера Первая свежесть",
    brend: "Первым делом",
    description:
      "Филе грудки — вкусное и полезное мясо. Это диетический продукт обладает нейтральным вкусом, отлично сочетается практически с любым гарниром. ",
    price: 449,
    cents: 90,
    image: meat13,
    country: "Россия",
    calories: 140,
    proteins: 18,
    fats: 8,
    carbohydrates: 4,
    category: "meat",
    subcategories: "bird",
    type: "nopopular",
  },
  {
    id: 44,
    name: "Фарш говяжий Мясоедов 400г",
    brend: "Дикси",
    description:
      "Фарш говяжий подходит для приготовления котлет, тефтелей, фрикаделек. Из него получится великолепный соус Болоньезе или пельмени.",
    price: 199,
    cents: 90,
    image: meat14,
    country: "Россия",
    calories: 369,
    proteins: 12,
    fats: 35,
    carbohydrates: 0,
    category: "meat",
    subcategories: "groundmeat",
    type: "nopopular",
  },
  {
    id: 45,
    name: "Фарш Мясоедов Домашний 400г",
    brend: "Дикси",
    description:
      "Фарш Домашний - это мясной полуфабрикат, приготовленный из говядины и свинины. Он используется для приготовления котлет, тефтелей, фрикаделек",
    price: 139,
    cents: 90,
    image: meat15,
    country: "Россия",
    calories: 363,
    proteins: 12,
    fats: 35,
    carbohydrates: 2.5,
    category: "meat",
    subcategories: "groundmeat",
    type: "nopopular",
  },
  {
    id: 46,
    name: "Фарш Пава-Пава Нежный из индейки охлажденный 450г",
    brend: "Пава-Пава",
    description:
      "Фарш 'Нежный' Пава изготовлен из мяса цыпленка индейки. Он не содержит Е-добавок, прекрасно подходит для приготовления фрикаделек, тефтелей, котлет",
    price: 199,
    cents: 90,
    image: meat16,
    country: "Россия",
    calories: 140,
    proteins: 18,
    fats: 7,
    carbohydrates: 0,
    category: "meat",
    subcategories: "groundmeat",
    type: "nopopular",
  },
  {
    id: 47,
    name: "Фарш Мираторг говяжий охлажденный 400г",
    brend: "Мираторг",
    description:
      "Говяжий фарш от ТМ «Мираторг» — 100% говядина и ничего лишнего! Это рубленое мясо бычков породы Black Angus, выращенных в Брянской области, станет основой",
    price: 194,
    cents: 90,
    image: meat17,
    country: "Россия",
    calories: 360,
    proteins: 12,
    fats: 35,
    carbohydrates: 0,
    category: "meat",
    subcategories: "groundmeat",
    type: "nopopular",
  },
  {
    id: 48,
    name: "Котлеты Слово мясника Сливочные охлажденные 360г",
    brend: "Слово мясника",
    description:
      "Котлеты СЛОВО МЯСНИКА – оптимальный вариант для того, чтобы быстро приготовить вкусный ужин или обед. Котлеты можно обжарить на сковороде, потушить с овощами или крупами в мультиварке, а также запечь в духовке.",
    price: 161,
    cents: 90,
    image: meat18,
    country: "Россия",
    calories: 360,
    proteins: 12,
    fats: 35,
    carbohydrates: 0,
    category: "meat",
    subcategories: "cutlet",
    type: "nopopular",
  },
  {
    id: 49,
    name: "Котлеты Петелинка куриные сливочные охлажденные 500г",
    brend: "Петелинка",
    description:
      "По-домашнему вкусные «Сливочные» котлеты — это охлажденный панированный полуфабрикат, приготовленный из фарша цыплят-бройлеров с добавлением молока, сливочного масла и пряностей: ароматного чеснока, лука, тмина, базилика. Колеты бренда «Петелинка» готовятся очень быстро, равномерно прожариваясь со всех сторон, их отличает сочный нежный вкус и привлекательный аромат. Подавать рекомендуется с соусами и любыми гарнирами.",
    price: 179,
    cents: 90,
    image: meat19,
    country: "Россия",
    calories: 200,
    proteins: 14,
    fats: 15,
    carbohydrates: 2,
    category: "meat",
    subcategories: "cutlet",
    type: "nopopular",
  },
  {
    id: 50,
    name: "Котлеты Троекурово Деревенские куриные охлажденные 400г",
    brend: "Троекурово",
    description:
      "Котлеты куриные Троекурово Деревенские 400г - это охлажденный полуфабрикат, приготовленный по фирменному рецепту из рубленого филе цыпленка-бройлера. Вкусные и аппетитные котлетки без панировки очень похожи на домашние; они такие же сочные, нежные, с натуральным вкусом отборного куриного мяса. Их можно приготовить двумя способами: запечь в разогретой до 150-200°С духовке в течение 10-15 минут или обжарить на раскаленной сковороде (сначала на сильном огне, а затем под крышкой на медленном). Продукция торговой марки 'Троекурово' производится из птицы, выращенной на отечественном корме без ГМО и гормонов роста, что позволяет сохранить натуральный вкус и максимум питательной ценности куриного мяса.",
    price: 129,
    cents: 90,
    image: meat20,
    country: "Россия",
    calories: 190,
    proteins: 17,
    fats: 12,
    carbohydrates: 4,
    category: "meat",
    subcategories: "cutlet",
    type: "nopopular",
  },
  {
    id: 51,
    name: "Фрикадельки Ближние горки свиные охлажденные 360г",
    brend: "Ближние Горки",
    description:
      "Полуфабрикат мясной из свинины рубленый формованный категория В. Упаковано в модифицированной атмосфере. Срок годности после вскрытия: 12 часов. Фрикадельки универсальный мясной продукт, идеально подойдет для жарки и для варки, и для запекания в духовке. Классический мясной вкус, дополненный ароматными специями, никого не оставит равнодушным.",
    price: 139,
    cents: 90,
    image: meat21,
    country: "Россия",
    calories: 300,
    proteins: 12,
    fats: 28,
    carbohydrates: 0,
    category: "meat",
    subcategories: "cutlet",
    type: "nopopular",
  },
    {
    id:52,
    name: "Томаты Азербайджанские розовые",
    brend: "Azfood",
    description:
      "Бакинские розовые помидоры отличаются небольшим размером, имеют тонкую кожицу и мясистую, сочную, сладкую мякоть. Выращены в экологически чистом районе Азербайджана. Интересный факт: в розовых томатах витамина С и антиоксидантов втрое больше, чем в красных.",
    price: 199,
    cents: 90,
    image: fruit1,
    country: "Azerbajan",
    calories: 20,
    proteins: 1.1,
    fats: 0.2,
    carbohydrates: 3.7,
    category: "fruits",
    subcategories: "овоши",
    type: "nopopular",
  },
      {
    id:53,
    name: "Огурцы короткоплодные тепличные",
    brend: "Azfood",
    description:
      "Короткоплодные бугорчатые огурцы идеально сочетают в себе насыщенный аромат, яркий вкус и приятный хруст. Небольшие огурчики можно добавлять в салаты, закуски или есть свежими. Очень вкусно, попробуйте!",
    price: 159,
    cents: 90,
    image: fruit2,
    country: "Azerbajan",
    calories: 15,
    proteins: 0.8,
    fats: 0.1,
    carbohydrates: 2.8,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
        {
    id:54,
    name: "Лук репчатый",
    brend: "Belarusfood",
    description:
      "Лук репчатый - это пряное растение с резким запахом и островатым вкусом, которое употребляется как основной или вспомогательный ингредиент, без преувеличения, во всех кухнях мира. Он входит в состав свежих салатов, маринадов, соусов, зажарок, добавляется в консервированные овощи, мясные и рыбные блюда.",
    price: 61,
    cents: 99,
    image: fruit3,
    country: "Belarus",
    calories: 41,
    proteins: 1.4,
    fats: 0.2,
    carbohydrates: 8.2,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
        {
    id:55,
    name: "Картофель молодой",
    brend: "Belarusfood",
    description:
      "Картофель - это доступный, сытный, универсальный корнеплод, любимый во всем мире. Он отличается высокими питательными и вкусовыми качествами, богат витаминами и минеральными веществами, является основой многих гарниров и самостоятельных блюд.",
    price: 81,
    cents: 99,
    image: fruit4,
    country: "Belarus",
    calories: 77,
    proteins:2,
    fats: 0.4,
    carbohydrates: 16.3,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
          {
    id:56,
    name: "Томаты черри в упаковке, 250 г",
    brend: "Russiafood",
    description:
      "Томаты черри – источник микроэлементов и минералов, необходимых организму. Помидоры на ветке выглядят эффектно благодаря крупной кисти, схожей по форме с гроздью винограда. Ароматные и сладкие мини-томаты идеально подойдут как для употребления в свежем виде, так и для консервации.",
    price: 149,
    cents: 99,
    image: fruit5,
    country: "Russia",
    calories: 14,
    proteins:0.6,
    fats: 0,
    carbohydrates: 2.9,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
            {
    id:57,
    name: "Баклажаны крупные",
    brend: "Russiafood",
    description:
      "Баклажаны используются в пищу в недозрелом виде, когда они имеют красивую фиолетовую окраску. Сырыми баклажаны употреблять не рекомендуется. В приготовленном виде баклажаны имеют нежный, слегка пряный вкус. Баклажаны хорошо сочетаются с любыми овощами, сыром.",
    price: 179,
    cents: 99,
    image: fruit6,
    country: "Russia",
    calories: 24,
    proteins:1.2,
    fats: 0.1,
    carbohydrates: 4.5,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
              {
    id:58,
    name: "Чеснок в упаковке, 1 шт",
    brend: "Russiafood",
    description:
      "Чеснок славится за счет своих полезных свойств и большого уровня содержания витаминов. Он прекрасно сочетается с мясом, овощами, имбирем и томатами. Из него можно приготовить множество различных соусов для блюд. Чеснок часто используют для приготовления маринадов. Он является неотъемлемым ингредиентом популярного в России плова.",
    price: 79,
    cents: 99,
    image: fruit7,
    country: "Russia",
    calories: 143,
    proteins:6,
    fats: 0.5,
    carbohydrates: 29.9,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
              {
    id:59,
    name: "Картофель молодой Египет в упаковке",
    brend: "Egiptfood",
    description:
      "Египетский картофель отличается ровными, слегка продолговатыми клубнями и тонкой кожурой. Молодой картофель подходит для различных кулинарных экспериментов. Он будет вкусным и в обжаренном виде, и «в мундире», и запечённым. Картофель очищен от излишков земли и не имеет глубоких глазков, поэтому его довольно легко чистить.",
    price: 99,
    cents: 99,
    image: fruit8,
    country: "Egipt",
    calories: 76,
    proteins:2,
    fats: 0.4,
    carbohydrates: 16,
    category: "fruits",
    subcategories: "овощи",
    type: "nopopular",
  },
               {
    id:60,
    name: "Бананы спелые",
    brend: "Egiptfood",
    description:
      "Спелые и сладкие бананы не нуждаются в представлении: этот тропический фрукт — один из самых популярных в России! Бананы обладают плотной, сладкой мякотью и освежающим ароматом с травянистыми нотками.Цветность банана может колебаться от преобладания желтого, с зеленым кончиком, до полностью желтой.",
    price: 129,
    cents: 99,
    image: fruit9,
    country: "Egipt",
    calories: 96,
    proteins:1.5,
    fats: 0.5,
    carbohydrates: 21,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                 {
    id:61,
    name: "Черешня сезонная",
    brend: "Armeniafood",
    description:
      "Ягоды черешни имеют форму стилизованного сердца, упругую, сочную и «мясистую» мякоть, сладкий вкус и нежный аромат. Черешня используется в производстве йогуртов, творожных продуктов, соков и других напитков, десертов, варенья, мороженого, цукатов.",
    price: 399,
    cents: 99,
    image: fruit10,
    country: "Armenia",
    calories: 63,
    proteins:1.06,
    fats: 0.2,
    carbohydrates: 13.91,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                 {
    id:62,
    name: "Абрикосы свежие",
    brend: "Armeniafood",
    description:
      "Плоды абрикоса с желто-оранжевой бархатистой кожицей и сочной волокнистой мякотью не только выглядят красиво, имеют приятный вкус и полезные свойства, но и утоляют голод и жажду, содержат много витаминов и клетчатки, а Энергетическая ценность этого идеального продукта для легкого перекуса низкая.",
    price: 179,
    cents: 99,
    image: fruit11,
    country: "Armenia",
    calories: 44,
    proteins:0.9,
    fats: 0.1,
    carbohydrates: 9,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                   {
    id:63,
    name: "Апельсины Новый урожай",
    brend: "Armeniafood",
    description:
      "Недаром апельсин называют всемогущим цитрусом. “Яркое солнышко” может похвалиться богатейшим набором витамина С, органических кислот, пектина, минералов и других не менее полезных веществ. Диетологи предлагают выбрать этот цитрус для регулирования жирового обмена в организме.",
    price: 119,
    cents: 99,
    image: fruit12,
    country: "Armenia",
    calories: 36,
    proteins:0.9,
    fats: 0.2,
    carbohydrates: 8.1,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                  {
    id:64,
    name: "Яблоки сезонные",
    brend: "Armeniafood",
    description:
      "Спелые плоды сезонных яблок отличаются ароматной кожицей и сочной мякотью, во вкусе которой звучат яркая гармония кислых и сладких нот. Рекомендуем полакомиться яблоками в свежем виде или использовать для приготовления сухофруктов, компотов, соков, начинки для десертов и выпечки. Хранить в холодильнике",
    price: 126,
    cents: 99,
    image: fruit13,
    country: "Armenia",
    calories: 55,
    proteins:0.26,
    fats: 0.17,
    carbohydrates: 13.8,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                {
    id:65,
    name: "Лимоны сочные",
    brend: "TurkeyFood",
    description:
      "Лимоны с тонкой кожурой подходят для чая. Они очень ароматные, кислые, сочные. Эти лимоны также отлично украсят рыбное ассорти и тарелку морепродуктов. Долька такого лимона станет лучшим дополнением к стейку из семги и креветкам. Из лимонов такого сорта делают домашний лимонад: благодаря яркому аромату и вкусу плодов напиток получается освежающим и тонизирующим.",
    price: 199,
    cents: 99,
    image: fruit14,
    country: "Turkey",
    calories: 34,
    proteins:0.9,
    fats: 0.11,
    carbohydrates: 3,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                 {
    id:66,
    name: "Персики плоские",
    brend: "TurkeyFood",
    description:
      "Плод имеет розово-бордовый цвет, средний размер и приплюснутую форму. На вкус эти фрукты достаточно сладкие и сочные, их нежная мякоть покрыта тонкой бархатистой кожурой. Благодаря небольшой калорийности персики рекомендуется употреблять в пищу людям на диете или приверженцам правильного питания.",
    price: 299,
    cents: 99,
    image: fruit15,
    country: "Turkey",
    calories: 58.6,
    proteins:0.9,
    fats: 0.1,
    carbohydrates: 15.5,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                   {
    id:67,
    name: "Груша Конференц/Аббат",
    brend: "TurkeyFood",
    description:
      "Любимые многими груши сорта Конференция/Аббат сладкие, хрустящие и ароматные! Груши долго хранятся и в процессе хранения становятся мягче и слаще. Плоды вытянутой формы имеют зеленую кожицу, покрытую матово-коричневым напылением и плотную, сочную, сладкую мякоть.",
    price: 199,
    cents: 99,
    image: fruit16,
    country: "Turkey",
    calories: 67,
    proteins:0.36,
    fats: 0.09,
    carbohydrates: 16.1,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                     {
    id:68,
    name: "Нектарины спелые",
    brend: "TurkeyFood",
    description:
      "Нектарин – это фрукт, представляющий собой персик с гладкой кожицей. Названия плода происходит от слова «нектар», так как характеризуется повышенным содержанием сахара - нектара. Из-за отсутствия пушка фрукт выглядит очень ярко. Мякоть желтая, плотная, сочная, сладкая, легко отделяется от косточки.",
    price: 299,
    cents: 99,
    image: fruit17,
    country: "Turkey",
    calories: 44,
    proteins:1.06,
    fats: 0.32,
    carbohydrates: 8.85,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                       {
    id:69,
    name: "Мандарины сладкие",
    brend: "AbxaziaFood",
    description:
      "Родиной этих мандаринов являются южные страны Африки. Под тропическим солнцем созревают небольшие фрукты с тонкой ярко-оранжевой кожицей, которая легко снимается. Под ней - 7-8 долек сладкой сочной мякоти. Этот морозоустойчивый сорт привозят в Россию ранней весной и поздней осенью. Он долго хранится в домашних условиях.",
    price: 194,
    cents: 99,
    image: fruit18,
    country: "Abxazia",
    calories: 38,
    proteins:0.8,
    fats: 0.2,
    carbohydrates: 7.5,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                      {
    id:70,
    name: "Виноград светлый",
    brend: "AbxaziaFood",
    description:
      "Светлый виноград известен простым и нежным вкусом. Удлиненные желто-зеленые ягоды имеют большие размеры, весят 8-10 г. Грозди у этого сорта крупные, умеренно плотные, рыхлые. Хранить в холодильнике.",
    price: 329,
    cents: 99,
    image: fruit19,
    country: "Abxazia",
    calories: 65,
    proteins:0.6,
    fats: 0.2,
    carbohydrates: 16.8,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
                      {
    id:71,
    name: "Арбуз импортный",
    brend: "IranFood",
    description:
      "Арбуз — сладкая ягода с освежающей, сочной мякотью. Его можно есть в свежем виде или добавлять в необычные салаты и варенья, обжаривать с сыром и ветчиной, готовить на гриле. Продукт сочетают с фруктами, ягодами, мороженым, оливковым маслом, рассольными сырами.",
    price: 329,
    cents: 99,
    image: fruit20,
    country: "Iran",
    calories: 65,
    proteins:0.6,
    fats: 0.2,
    carbohydrates: 16.8,
    category: "fruits",
    subcategories: "fruit",
    type: "nopopular",
  },
];
